- name: Go
  logo: golang
  url: 'https://go.dev/'
  color: '#85d3fd'
  projects:
    - url: 'https://github.com/getstackhead/stackhead'
    
- name: Node.js
  logo: nodedotjs
  url: 'https://nodejs.org/'
  color: '#339933'
  projects:
    - url: 'https://github.com/saitho/semantic-release-gitea'
    
- name: PHP
  logo: php
  url: 'https://www.php.net/'
  color: '#777BB4'
  projects:
    - url: 'https://github.com/saitho/saitho-cli'
    
- name: TypeScript
  logo: typescript
  url: 'https://www.typescriptlang.org/'
  color: '#2973ce'
  projects:
    - url: 'https://github.com/saitho/twitter-translator-bot'
    - url: 'https://github.com/saitho/amp-css'
    - url: 'https://github.com/saitho/bingo'
    - url: 'https://github.com/saitho/ts-appversion'
    - url: 'https://github.com/saitho/semantic-release-backmerge'
