# Action to generate metrics using LowLighter/Metrics by Simon Lecoq

# All results are in SVG format, and commited to /assets/metrics/ in master branch.
# Split into multiple jobs, to prevent everything failing if one component errors,
# And to improve the loading and layout of /METRICS.md where the SVGs are displayed

name: 📊 Generates Metrics
on:
  schedule:
    - cron: '40 23 * * *' # Run every evening, twenty mins before midnight
  workflow_dispatch: # Or when it's manually triggered
jobs:  
  # Coding Habits
  coding-habits-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          filename: assets/metrics/habits.svg
          committer_message: "📊 Updates metrics - habbits"
          user: saitho
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          plugin_habits_days: 28
          plugin_habits_from: 500
          config_timezone: Europe/Berlin

  # Recent Activity
  activity-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: assets/metrics/activity.svg
          committer_message: "📊 Updates metrics - activity"
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: saitho
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 15
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create, public

          
  # Languages that code is written in
  language-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: assets/metrics/languages.svg
          committer_message: "📊 Updates metrics - languages"
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: saitho
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15
          plugin_languages_recent_days: 120
          plugin_languages_other: yes
          plugin_languages_sections: most-used, recently-used

  # Achievments, fake awards showing that i have no life
  acheiment-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: assets/metrics/achievements.svg
          committer_message: "📊 Updates metrics - acheivments"
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: saitho
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_display: detailed
   
 # Starred Topics
  starred-topics-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: assets/metrics/topics.svg
          committer_message: "📊 Updates metrics - topics"
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: saitho
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 20
          plugin_topics_mode: icons
          
  # All Metrics together
  all-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: assets/metrics/all.svg
          committer_message: "📊 Updates metrics - all"
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          # Options
          user: saitho
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Berlin
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list
          plugin_sponsors_size: 24
          plugin_traffic: yes
          plugin_gists: yes
          plugin_discussions: yes

  # Main Metrics - Short
  shorter-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: assets/metrics/summary.svg
          committer_message: "📊 Updates metrics - summary"
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: saitho
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Europe/Berlin
          plugin_achievements: no
          plugin_followup: no
          plugin_habits: no
          plugin_introduction: no
          plugin_introduction_title: no
          plugin_lines: yes
          plugin_notable: no
          plugin_notable_from: all
          plugin_notable_types: commit
          plugin_people: no
          plugin_projects: no
          plugin_reactions: no
          plugin_sponsors: no
          plugin_traffic: yes
          plugin_gists: no
          plugin_discussions: no
